feat(search): add `ctrl-y` keybind and subcommand picker

diff --git a/gh-fzf b/gh-fzf
--- a/gh-fzf
+++ b/gh-fzf
@@ -758,54 +758,78 @@ Filters > (alt-p: public) (alt-s: secret)
 
 # COMMAND > SEARCH                                                      {{{1
 search_cmd() {
-    SEARCH_SUBCOMMAND="$1"
-
-    case $SEARCH_SUBCOMMAND in
-        issues) SEARCH_OPEN_COMMAND="gh issue view --web {2} --repo {1}" ;;
-        prs) SEARCH_OPEN_COMMAND="gh pr view --web {2} --repo {1}" ;;
-        repos) SEARCH_OPEN_COMMAND="gh repo view --web {1}" ;;
-        commits) SEARCH_OPEN_COMMAND="$GH_FZF_OPEN_CMD https://github.com/{1}/commit/{2}" ;;
-        code)
-            # shellcheck disable=2089
-            SEARCH_SUBCOMMAND_OPTS="--header-lines=2 --read0 --highlight-line"
-            MULTILINE_CHUNKER="| perl -0 -pe 's/^\n/\n\0/gm'"
-            ;;
-        *)
-            error "invalid search command: \"$1\"" \
-                "Valid commands: issues, prs, repos, commits, code"
-            ;;
-    esac
-    shift
+    if [ -n "$1" ]; then
+        search_subcmd="$1"
+        case $search_subcmd in
+            issues | prs)
+                search_open_cmd="gh issue view --web {2} --repo {1}"
+                search_copy_cmd="gh issue view --json url --jq .url {2} --repo {1}"
+                ;;
+            repos)
+                search_open_cmd="gh repo view --web {1}"
+                search_copy_cmd="gh repo view --json url --jq .url {1}"
+                ;;
+            commits)
+                search_open_cmd="$GH_FZF_OPEN_CMD \"https://github.com/{1}/commit/{2}\""
+                search_copy_cmd="echo \"https://github.com/{1}/commit/{2}\" | $GH_FZF_COPY_CMD"
+                ;;
+            code)
+                # NOTE: requires fzf >= v0.53.0 for multiline support
+                # https://github.com/junegunn/fzf/releases/tag/0.53.0
+                multiline_chunker="| perl -0 -pe 's/^\n/\n\0/gm'"
+                search_subcmd_opts="--header-lines=2 --read0 --highlight-line"
+                ;;
+            *)
+                error "invalid search command: \"$search_subcmd\"" \
+                    "Valid commands: issues, prs, repos, commits, code"
+                ;;
+        esac
+        shift
+    else
+        FZF_DEFAULT_COMMAND="printf '%s\n' issues prs repos commits code" \
+            fzf --ansi --header="COMMAND" --header-lines=0 \
+            --bind="resize:refresh-previdew" \
+            --preview='GH_FORCE_TTY=$FZF_PREVIEW_COLUMNS gh help search {}' \
+            --preview-window='right,75%,wrap,<75(down,border-top,75%,wrap)' \
+            --bind="enter:execute(gh fzf search {})"
+        exit
+    fi
 
     # FZF COMMAND      {{{2
-    SEARCH_COMMAND="GH_FORCE_TTY=$GH_COLUMNS gh search $SEARCH_SUBCOMMAND -L $GH_FZF_DEFAULT_LIMIT"
+    search_cmd="GH_FORCE_TTY=$GH_COLUMNS gh search $search_subcmd -L $GH_FZF_DEFAULT_LIMIT"
 
-    # shellcheck disable=2090
     fzf \
         --delimiter="\s\s+" \
         --header-lines=4 \
         --disabled \
         --query="$*" \
+        $search_subcmd_opts \
         --border="bottom" \
         --border-label="[mode: gh] " \
         --border-label-pos=-99999 \
-        --prompt="search $SEARCH_SUBCOMMAND ❱ " \
-        --bind="start:reload($SEARCH_COMMAND \$FZF_QUERY $MULTILINE_CHUNKER || true)${GH_FZF_HIDE_HINTS:+"+toggle-header"}" \
-        --bind "change:reload-sync:sleep 0.25; $SEARCH_COMMAND \$FZF_QUERY $MULTILINE_CHUNKER || true" \
+        --prompt="search $search_subcmd ❱ " \
+        --bind="start:${GH_FZF_HIDE_HINTS:+"toggle-header+"}reload(
+            $search_cmd \$FZF_QUERY $multiline_chunker || true
+        )" \
+        --bind "change:reload-sync:sleep 0.25; $search_cmd \$FZF_QUERY $multiline_chunker || true" \
         --bind 'alt-/:transform:[[ ! $FZF_BORDER_LABEL =~ gh ]] &&
-            echo "rebind(change)+change-border-label([mode:  gh] )+disable-search+transform-query(
-                echo \{q} > ${TMPDIR:-/tmp}/gh-fzf-search-query-fzf;
-                cat ${TMPDIR:-/tmp}/gh-fzf-search-query-gh
-            )+reload-sync('"$SEARCH_COMMAND"' $FZF_QUERY || true)" ||
-            echo "unbind(change)+change-border-label([mode: fzf] )+enable-search+transform-query(
-                echo \{q} > ${TMPDIR:-/tmp}/gh-fzf-search-query-gh;
-                cat ${TMPDIR:-/tmp}/gh-fzf-search-query-fzf
-            )"' \
+            echo "change-border-label([mode:  gh] )+transform-query(
+                    echo \{q} > ${TMPDIR:-/tmp}/gh-fzf-search-query-fzf;
+                    cat ${TMPDIR:-/tmp}/gh-fzf-search-query-gh
+                )+rebind(change)+disable-search+reload-sync(
+                    '"$search_cmd"' $FZF_QUERY || true
+                )" ||
+            echo "change-border-label([mode: fzf] )+transform-query(
+                    echo \{q} > ${TMPDIR:-/tmp}/gh-fzf-search-query-gh;
+                    cat ${TMPDIR:-/tmp}/gh-fzf-search-query-fzf
+                )+unbind(change)+enable-search"
+        ' \
         --bind='ctrl-r:execute-silent(
             rm -f  ${TMPDIR:-/tmp}/gh-fzf-search-query-{gh,fzf}
-        )+clear-query+first+reload:'"$SEARCH_COMMAND" \
-        --bind="ctrl-o:execute-silent($SEARCH_OPEN_COMMAND)" \
-        $SEARCH_SUBCOMMAND_OPTS
+        )+clear-query+first+reload:'"$search_cmd" \
+        --bind="ctrl-o:execute-silent:$search_open_cmd &" \
+        --bind="ctrl-y:execute-silent:$search_copy_cmd" \
+        </dev/null
 
     #2}}}
 }
